import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const SRC_DIR = join(dirname(fileURLToPath(import.meta.url)));

const SHARED_SOURCES = ['es3-polyfills.js', 'es3-json2.js', 'bridge-fs.js'];

const PAYLOAD_SOURCES = [...SHARED_SOURCES, 'job-runner.js'];
const LOADER_SOURCES = [...SHARED_SOURCES, 'loader.js'];

async function bridgeVersion(): Promise<string> {
  const pkg = JSON.parse(await readFile(join(SRC_DIR, '..', 'package.json'), 'utf8'));
  return pkg.version;
}

function stamp(version: string): string {
  return [
    '/**',
    ' * ae-mcp bridge. Generated by packages/bridge/src/build.ts. DO NOT EDIT.',
    ` * bridge version: ${version}`,
    ` * built: ${new Date().toISOString()}`,
    ' */',
    `var AEMCP_BRIDGE_VERSION = "${version}";`,
    '',
  ].join('\n');
}

async function concat(sources: string[]): Promise<string> {
  const bodies = await Promise.all(
    sources.map((name) => readFile(join(SRC_DIR, name), 'utf8')),
  );
  return bodies.join('\n');
}

export async function build(
  options: { outDir?: string } = {},
): Promise<{ loader: string; payload: string }> {
  const outDir = options.outDir ?? join(SRC_DIR, '..', 'dist');
  const version = await bridgeVersion();
  const head = stamp(version);
  const loader = `${head}${await concat(LOADER_SOURCES)}`;
  const payload = `${head}${await concat(PAYLOAD_SOURCES)}`;
  await mkdir(outDir, { recursive: true });
  await writeFile(join(outDir, 'loader.jsx'), loader);
  await writeFile(join(outDir, 'payload.jsx'), payload);
  return { loader, payload };
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  build().catch((error) => {
    console.error(error);
    process.exit(1);
  });
}